---
- name: checking for agent install
  win_stat:
    path: '{{ windows_bit9_agent_path }}'
  register: path

- debug:
    msg: "bit9 agent not found"
  when: path.stat.islnk is not defined

- debug:
    msg: "bit9 agent found skipping install"
  when: path.stat.islnk is defined

- name: create {{ windows_agent_log }} directory
  win_file:
    path: '{{ windows_agent_log }}'
    recurse: yes
    state: directory
    validate_certs: no
  when: path.stat.islnk is not defined

- name: install bit9 agent (windows)
  win_package:
    path: '{{ windows_bit9_agent_url }}'
    log_path: '{{ windows_agent_log }}\\bit9_log.txt'
    product_id: '{{ windows_bit9_product_id }}'
    validate_certs: no
    state: present
    arguments: /qn
  when: path.stat.islnk is not defined

- name: verify bit9 started
  win_service:
    name: parity
    state: started
