---
- name: create win_agent_path directory
  win_file:
    path: '{{ win_agent_path }}'
    state: directory
  when: ansible_os_family = 'Windows'

- name: create win_agent_logs directory
  win_file:
    path: '{{ win_agent_logs }}'
    state: directory
  when: ansible_os_family = 'Windows'

- name: install carbon black protector agent (windows)
  win_package:
    path: '{{ win_agent_path }}\\{{ item.name }}'
    chdir: '{{ win_agent_path }}'
    state: present
    log_path: '{{ win_agent_logs }}\\{{ item.name }}_log.txt'
    validate_certs: no
  with_items:
    - { name: '{{ windows_bit9_agent_filename }}' }
  when: ansible_os_family = 'Windows'
