---
- name: create {{ win_agent_path }} directory
  win_file:
    path: '{{ win_agent_path }}'
    state: directory
  when: ansible_os_family == 'Windows'

- name: create {{ win_agent_logs }} directory
  win_file:
    path: '{{ win_agent_logs }}'
    state: directory
  when: ansible_os_family == 'Windows'

- name: checking for installer
  win_stat:
    path: '{{ win_agent_path }}{{ windows_bit9_agent_filename }}'
  register: installer
  when: ansible_os_family == 'Windows'

# replace with S3 method
- name: move installer to {{ win_agent_path }} directory
  win_copy:
    src: '{{ lin_agent_path }}/{{ item.name }}'
    dest: '{{ win_agent_path }}{{ item.name }}'
  with_items:
    - { name: '{{ windows_bit9_agent_filename }}'}
  when: ansible_os_family == 'Windows' and installer.stat.exists

- name: install bit9 agent (windows)
  win_package:
    path: '{{ win_agent_path }}\\{{ item.name }}'
    chdir: '{{ win_agent_path }}'
    state: present
    log_path: '{{ win_agent_logs }}\\{{ item.name }}_log.txt'
    validate_certs: no
  with_items:
    - { name: '{{ windows_bit9_agent_filename }}' }
  when: ansible_os_family == 'Windows'
