---
- name: checking for agent install
  win_service:
    name: parity
  register: agent

- debug:
    msg: "bit9 agent not found (installing)"
  when: not agent.exists

- debug:
    msg: "bit9 agent found (skipping install)"
  when: agent.exists

- debug:
    msg: "bit9 agent not found"
  when: agent.exists

- debug:
    msg: "bit9 agent found skipping install"
  when: not agent.exists

- name: create {{ windows_agent_log }} directory
  win_file:
    path: '{{ windows_agent_log }}'
    recurse: yes
    state: directory
  when: not agent.exists

- name: install bit9 agent (windows)
  win_package:
    path: '{{ windows_bit9_agent_url }}'
    log_path: '{{ windows_agent_log }}\bit9_log.txt'
    product_id: '{{ windows_bit9_product_id }}'
    state: present
    arguments: /qn
  when: not agent.exists

- name: verify bit9 started
  win_service:
    name: parity
    state: started
    start_mode: auto
